# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: X Wang
title: Full Stack Web Developer
email: xwang.dev@gmail.com
website: xwang1000.github.io

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: xuenan-wang
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am X, a junior full stack web developer. 

  I am most skilled in: <mark>front-end development</mark> and <mark>drinking artisan tea</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in web development some of my other interests and hobbies are:
   - Tea Drinking
   - Oriental Bellydancing
   - Fashion Design

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
